name: 2-Code Format
run-name: CI Pipeline - Code Format

on:
  workflow_run:
    workflows: ["1-Python Check"]
    types:
      - completed
    branches: [ main, master ]

jobs:
  format:
    name: Code Format
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install --no-interaction
          
      - name: Format imports with isort
        run: |
          poetry run isort .
          
      - name: Format code with Black
        run: |
          poetry run black .
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: Format code with isort and black"
          branch: ${{ github.ref_name }}